name: Publish

on:
  push:

permissions:
  # Need `contents: read` to checkout the repository.
  # Need `contents: write` to update the step metadata.
  contents: write

  
jobs:
  # Get the current step to only run the main job when the learner is on the same step.
  docker_publish:
    name: Docker Publish 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: dmevanct/skill-publish-packages:latest

